easy_admin:
    site_name: 'Gestion Blog REF-MED'
    user:
        display_name: true
        display_avatar: true
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        menu:
            - {label: 'Articles'}
            - {entity: 'Articles', label: 'Articles', icon: 'book'}
            - {entity: 'Categories', label: 'Categories', icon: 'tag'}
            - {entity: 'Keyword', label: 'Mots-Cles', icon: 'tag'}
            - {label: 'Utilisateurs du Blog'}
            - {entity: 'UsersBlog', label: 'Utilisateurs du Blog', icon: 'user'}
    formats:
        datetime: 'd/m/Y à H:i'   
    entities:
        Articles:
            # Correspond au fichier Articles.php
            class: App\Entity\Articles
            # On définit ci-dessous le contenu de la liste qui affichera les articles et les critères de tri
            list:
                fields:
                    - id
                    - { property: 'title', label: 'Titre'}
                    # Le champ ci-dessous affichera l'image de l'article
                    - { property: 'featuredImage', label: 'Image', type: 'image', base_path: '%app.path.featured%' }
                    - { property: 'createdAt', label: 'Créé' }
                    # Les catégories et les mots-clé sont listés ci-dessous
                    - { property: 'categories', label: 'Catégories', type: 'array'}
                    - { property: 'keywords', label: 'Mots-Clés', type: 'array'}
                    - { property: 'usersBlog', label: 'Auteur', type: 'entity'}
                sort: ['createdAt', 'desc']
            # On définit ci-dessous le contenu du formulaire d'ajout ou modification d'article
            form:
                fields:
                    - title
                    # Affichage de l'éditeur Wysiwyg
                    - { property: 'contenu', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}
                    # Affichage du champ d'ajout d'image
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - { property: 'usersBlog', label: 'Utilisateurs', type: 'entity', type_options: { class: 'App\Entity\UsersBlog' }} 
                    # Les catégories et mots-clés peuvent s'afficher avec une sélection multiple
                    - { property: 'categories', label: 'Catégories', type: 'entity', type_options: { class: 'App\Entity\Categories', multiple: true,by_reference: false, attr: { data-widget: 'select2' }}}
                    - { property: 'keywords', label: 'Mots Clés', type: 'entity', type_options: { class: 'App\Entity\keyword', multiple: true,by_reference: false, attr: { data-widget: 'select2' }}}
        Categories:
            class: App\Entity\Categories
            # On définit ci-dessous le contenu de la liste qui affichera les articles et les critères de tri
            list:
                fields:
                    - id
                    - articles
                    - { property: 'name', label: 'Nom de la categorie'}
                    - { property: 'fileName', label: 'Image', type: 'image', base_path: '%app.path.categories%' }
                    # Le champ ci-dessous affichera l'image de l'article
                    - { property: 'slug', label: 'Slug'}
                    - { property: 'articles', label: 'Article par catégorie', type: 'array'}
                sort: ['name', 'asc']
            # On définit ci-dessous le contenu du formulaire d'ajout ou modification d'article
            form:
                fields:
                    - name
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
        Keyword:
            # Correspond au fichier Articles.php
            class: App\Entity\Keyword
            label: 'Mots-Cles'
            # On définit ci-dessous le contenu de la liste qui affichera les articles et les critères de tri
            list:
                fields:
                    - id
                    - articles
                    - { property: 'keyword', label: 'Mots Cles'}
                    # Le champ ci-dessous affichera l'image de l'article
                    - { property: 'slug', label: 'Slug'}
                    - { property: 'articles', label: 'Article avec mots cles', type: 'array'}
                sort: ['keyword', 'asc']
            form:
                fields:
                    - keyword
        UsersBlog:
            class: App\Entity\UsersBlog
            label: 'Utilisateurs du Blog'
            # On définit ci-dessous le contenu de la liste qui affichera les articles et les critères de tri
            list:
                fields:
                    - id
                    - pseudo
                    - email
                    - { property: 'password', label: 'Mots de passe' }
                    - {property: 'filename', label: 'Image', type: 'image', base_path: '%app.path.avatar%' }
                sort: ['id', 'asc']
            form:
                fields:
                    - email
                    - pseudo
                    - password
                    - active
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - active
                    - { property: 'roles', type: 'choice', label: 'Rôles', type_options: {expanded: true, multiple: true, choices: {'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN', 'Moderateur': 'ROLE_MODO', } } }

                    