<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pharmacy extends \App\Entity\Pharmacy implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'pharmacyName', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'phoneNumber', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'enable', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'pharmacyAvailabeDrugs', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'meansPayment', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'location', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'pharmacySocialNetworks', 'roles', 'password'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'pharmacyName', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'phoneNumber', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'enable', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'pharmacyAvailabeDrugs', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'meansPayment', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'location', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Pharmacy' . "\0" . 'pharmacySocialNetworks', 'roles', 'password'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pharmacy $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPharmacyName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPharmacyName', []);

        return parent::getPharmacyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPharmacyName(string $pharmacyName): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPharmacyName', [$pharmacyName]);

        return parent::setPharmacyName($pharmacyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber(string $phoneNumber): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phoneNumber]);

        return parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture(?string $picture): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(string $slug): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnable(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnable', []);

        return parent::getEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnable(bool $enable): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnable', [$enable]);

        return parent::setEnable($enable);
    }

    /**
     * {@inheritDoc}
     */
    public function getPharmacyAvailabeDrugs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPharmacyAvailabeDrugs', []);

        return parent::getPharmacyAvailabeDrugs();
    }

    /**
     * {@inheritDoc}
     */
    public function addPharmacyAvailabeDrug(\App\Entity\PharmacyAvailabeDrugs $pharmacyAvailabeDrug): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPharmacyAvailabeDrug', [$pharmacyAvailabeDrug]);

        return parent::addPharmacyAvailabeDrug($pharmacyAvailabeDrug);
    }

    /**
     * {@inheritDoc}
     */
    public function removePharmacyAvailabeDrug(\App\Entity\PharmacyAvailabeDrugs $pharmacyAvailabeDrug): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePharmacyAvailabeDrug', [$pharmacyAvailabeDrug]);

        return parent::removePharmacyAvailabeDrug($pharmacyAvailabeDrug);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeansPayment(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeansPayment', []);

        return parent::getMeansPayment();
    }

    /**
     * {@inheritDoc}
     */
    public function addMeansPayment(\App\Entity\MeansPayment $meansPayment): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMeansPayment', [$meansPayment]);

        return parent::addMeansPayment($meansPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMeansPayment(\App\Entity\MeansPayment $meansPayment): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMeansPayment', [$meansPayment]);

        return parent::removeMeansPayment($meansPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation(): ?\App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(\App\Entity\Location $location): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile($imageFile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$imageFile]);

        return parent::setImageFile($imageFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getPharmacySocialNetworks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPharmacySocialNetworks', []);

        return parent::getPharmacySocialNetworks();
    }

    /**
     * {@inheritDoc}
     */
    public function addPharmacySocialNetwork(\App\Entity\PharmacySocialNetworks $pharmacySocialNetwork): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPharmacySocialNetwork', [$pharmacySocialNetwork]);

        return parent::addPharmacySocialNetwork($pharmacySocialNetwork);
    }

    /**
     * {@inheritDoc}
     */
    public function removePharmacySocialNetwork(\App\Entity\PharmacySocialNetworks $pharmacySocialNetwork): \App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePharmacySocialNetwork', [$pharmacySocialNetwork]);

        return parent::removePharmacySocialNetwork($pharmacySocialNetwork);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

}
