<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Location extends \App\Entity\Location implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'nameLocation', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'latitude', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'longitude', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'enable', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'doctor', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'laboratory', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'pharmacy'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'nameLocation', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'latitude', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'longitude', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'enable', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'doctor', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'laboratory', '' . "\0" . 'App\\Entity\\Location' . "\0" . 'pharmacy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Location $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNameLocation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameLocation', []);

        return parent::getNameLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameLocation(string $nameLocation): \App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameLocation', [$nameLocation]);

        return parent::setNameLocation($nameLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(string $slug): \App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude(?float $latitude): \App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude(?float $longitude): \App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnable(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnable', []);

        return parent::getEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnable(bool $enable): \App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnable', [$enable]);

        return parent::setEnable($enable);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoctor(): ?\App\Entity\Doctor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoctor', []);

        return parent::getDoctor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoctor(\App\Entity\Doctor $doctor): \App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoctor', [$doctor]);

        return parent::setDoctor($doctor);
    }

    /**
     * {@inheritDoc}
     */
    public function getLaboratory(): ?\App\Entity\Laboratory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaboratory', []);

        return parent::getLaboratory();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaboratory(\App\Entity\Laboratory $laboratory): \App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaboratory', [$laboratory]);

        return parent::setLaboratory($laboratory);
    }

    /**
     * {@inheritDoc}
     */
    public function getPharmacy(): ?\App\Entity\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPharmacy', []);

        return parent::getPharmacy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPharmacy(\App\Entity\Pharmacy $pharmacy): \App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPharmacy', [$pharmacy]);

        return parent::setPharmacy($pharmacy);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
