<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGknl0ZM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGknl0ZM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGknl0ZM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGknl0ZM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGknl0ZM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Gknl0ZM',
    'container.build_id' => 'b02fc213',
    'container.build_time' => 1586697384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGknl0ZM');
