<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1le9xA9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1le9xA9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1le9xA9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1le9xA9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1le9xA9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1le9xA9',
    'container.build_id' => '31384fab',
    'container.build_time' => 1591674681,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1le9xA9');
