<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI6GdlsC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI6GdlsC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI6GdlsC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI6GdlsC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerI6GdlsC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'I6GdlsC',
    'container.build_id' => '527265e6',
    'container.build_time' => 1586872363,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI6GdlsC');
