# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    filter_sets:
        thumbArticle:
            quality: 85
            filters: 
                thumbnail: { size: [320, 320], mode: outbound }
        featuredBigCategories:
            quality: 85
            filters: 
                thumbnail: { size: [819, 564], mode: outbound }
        featuredMinCategories:
            quality: 75
            filters: 
                thumbnail: { size: [410, 282], mode: outbound }
        featuredArticle:
            quality: 95
            filters: 
                thumbnail: { size: [960, 470], mode: outbound }
        avatarRow:
            quality: 95
            filters: 
                thumbnail: { size: [105, 85], mode: outbound }

