sonata_admin:
    dashboard:
        blocks:

            # display dashboard block in the top zone with a col-md-6 css class
            -
                position: top
                class: col-md-6
                type: language