# config/packages/sonata_admin.yaml
sonata_admin:
    title: 'REF-MED ADMINSTRATION'
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Gestion_pharmarcy, Gestion_Doctor, Gestion_Laboratoire]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Gestion_contenu_site, Gestion_infos]

        groups:
            Gestion_pharmarcy:
                items:
                    - admin.category_drugs
                    - admin.form_drugs
                    - admin.drugs_consomers

            Gestion_Doctor:
                items:
                    - sonata.page.admin.myitem2
                    - sonata.page.admin.myitem3

            Gestion_Laboratoire:
                items:
                    - sonata.page.admin.myitem4
            Gestion_contenu_site:
                items:
                    - sonata.page.admin.myitem4
            Gestion_infos:
                items:
                    - sonata.page.admin.myitem4
    global_search:
        empty_boxes: fade