# config/packages/sonata_admin.yaml

sonata_admin:
    dashboard:
        blocks:
            -
                class:    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  language   # admin code - service id
                    icon:  fa-magic                  # font awesome icon
                    text:  Language           # static text or translation message
                    color: bg-green                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        edited: { value: 1 }
      

