vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: '%app.path.avatar%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.avatar%'
        featuredImages:
            uri_prefix: '%app.path.featured%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.featured%'
        categoriesImages:
            uri_prefix: '%app.path.categories%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public/%app.path.categories%'
        pictureProfiles:
            uri_prefix: '%app.path.profile%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public/%app.path.profile%'
